In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
cd F:\nvb\KB-InfoBot

F:\nvb\KB-InfoBot


In [3]:
from deep_dialog.dialog_system import MovieDict, DictReader, Database
from deep_dialog.objects import SlotReader
from deep_dialog.agents.agent_nl_rule_soft import AgentNLRuleSoft
from deep_dialog.usersims import RuleSimulator
from deep_dialog.usersims.template_nlg import TemplateNLG
from deep_dialog.dialog_system.dialog_manager import DialogManager

In [4]:
params = {}
params['act_set'] = r'F:\nvb\KB-InfoBot\data\dia_acts.txt'
params['dataset'] = 'imdb_S'
params['tr'] = 1.0
params['ts'] = 1.0
params['max_req'] = 1
params['frac'] = 0.5
params['upd'] = 10
params['template_path'] = r'F:\nvb\KB-InfoBot\data\templates.j'

max_turn = 20
err_prob = .5
dk_prob = .5
sub_prob = .05
nlg_temp = 1
max_first_turn = 5


slot_path = r'F:\nvb\KB-InfoBot\data\imdb-S\slot_set.txt'
dict_path = r'F:/nvb/KB-InfoBot/data/imdb-S/dicts_.json'
db_full_path = r'F:\nvb\KB-InfoBot\data\imdb-S\db.txt'
db_inc_path = r'F:\nvb\KB-InfoBot\data\imdb-S\incomplete_db_0.20.txt'

In [5]:
act_set = DictReader()
act_set.load_dict_from_file(params['act_set'])

In [6]:
slot_set = SlotReader(slot_path)

In [7]:
movie_kb = MovieDict(dict_path)

In [8]:
db_full = Database(db_full_path, movie_kb, name=params['dataset'])
db_inc = Database(db_inc_path, movie_kb, name='incomplete_db_0.20')

In [9]:
db_inc.labels

['triple 9',
 'finding dory',
 'kung fu panda 3',
 'creed',
 'big short',
 'eddie the eagle',
 'where to invade next',
 'whiskey tango foxtrot',
 'deadpool',
 'batman vs superman',
 'lolo',
 'other side of the door',
 'forest',
 'young messiah',
 'brothers grimsby',
 'star wars',
 'zootopia',
 'how to be single',
 'risen',
 '10 cloverfield lane',
 'witch',
 'london has fallen',
 'room',
 'gods of egypt',
 'hail caesar',
 'race',
 'danish girl',
 'perfect match',
 'zoolander 2',
 'independce day',
 'spotlight',
 'the shawshank redemption',
 'the godfather',
 'the godfather: part ii',
 'the dark knight',
 "schindler's list",
 '12 angry men',
 'pulp fiction',
 'the lord of the rings: the return of the kin',
 'the good, the bad and the ugly',
 'fight club',
 'the lord of the rings: the fellowship of the ring',
 'star wars: episode v - the empire strikes bac',
 'forrest gump',
 'inception',
 'the lord of the rings: the two towers',
 "one flew over the cuckoo's nest",
 'goodfellas',
 'the ma

In [10]:
db_matches = [m[3] for m in db_full.tuples]
db_matches[:5]

['r', 'pg-13', 'pg-13', 'pg', 'pg-13']

In [11]:
db_inc.unks['actor']

array([  9,  10,  17,  19,  20,  28,  44,  51,  54,  57,  63,  67,  83,
        84,  86,  87,  88,  89,  90,  95,  98, 102, 114, 115, 119, 126,
       128, 138, 150, 153, 155, 160, 165, 166, 175, 186, 187, 189, 191,
       194, 196, 199, 202, 206, 210, 211, 215, 219, 220, 225, 233, 239,
       241, 244, 256, 259, 269, 270, 272, 273, 274], dtype=int64)

In [12]:
db_inc.ids['actor'].shape

(2, 277)

In [13]:
nlg = TemplateNLG(params['template_path'])

In [14]:
user_sim = RuleSimulator(movie_dict=movie_kb, act_set=act_set, slot_set=slot_set, 
                         start_set=None, max_turn=max_turn, nlg=nlg, err_prob=err_prob, 
                         db=db_full, dk_prob=(1.-dk_prob), sub_prob=sub_prob, 
                         max_first_turn=max_first_turn)

In [15]:
agent = AgentNLRuleSoft(movie_kb, act_set, slot_set, db_inc,
            upd=params['upd'], tr=params['tr'], ts=params['ts'], 
            frac=params['frac'], max_req=params['max_req'])

In [30]:
agent.initialize_episode()
agent.state

{'database': <deep_dialog.dialog_system.database.Database at 0x205133656c8>,
 'prevact': 'begin@begin',
 'inform_slots': {'actor': array([0.5092593 , 0.49074075], dtype=float32),
  'critic_rating': array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([0.34545454, 0.3272727 , 0.3272727 ], dtype=float32),
  'director': array([0.26339287, 0.26339287, 0.20089285, 0.27232143], dtype=float32),
  'release_year': array([0.06086956, 0.07391305, 0.07391305, 0.06956521, 0.06086956,
         0.08260869, 0.03478261, 0.04347826, 0.07391305, 0.07826087,
         0.04347826, 0.06956521, 0.03043478, 0.06086956, 0.07826087,
         0.06521739], dtype=float32)},
 'turn'

In [31]:
ua = user_sim.initialize_episode()
ua 

У искомой сущности есть слоты (в неполной БД) ['mpaa_rating', 'director', 'release_year']
Пользователь уже назвал (?): {'mpaa_rating': 'r'}


{'diaact': 'request',
 'turn': 0,
 'inform_slots': {'mpaa_rating': 'r'},
 'request_slots': {'movie': 'UNK'},
 'prev_diaact': 'UNK',
 'inform_slots_noisy': {'mpaa_rating': 'r'},
 'nl_sentence': 'Search for the movie which had r as mpaa_rating.',
 'episode_over': False,
 'reward': 0}

In [32]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  begin begin
Detected r  update =  1.0
Agent DB entropy =  7.077697
Agent slot belief entropies - 
actor:1.00 critic_rating:3.24 genre:3.65 mpaa_rating:0.79 director:1.99 release_year:3.93


{'database': <deep_dialog.dialog_system.database.Database at 0x205133656c8>,
 'prevact': 'request@release_year',
 'inform_slots': {'actor': array([0.5092593 , 0.49074075], dtype=float32),
  'critic_rating': array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([20.345455 ,  0.3272727,  0.3272727], dtype=float32),
  'director': array([0.26339287, 0.26339287, 0.20089285, 0.27232143], dtype=float32),
  'release_year': array([0.06086956, 0.07391305, 0.07391305, 0.06956521, 0.06086956,
         0.08260869, 0.03478261, 0.04347826, 0.07391305, 0.07826087,
         0.04347826, 0.06956521, 0.03043478, 0.06086956, 0.07826087,
         0.06521739], dtype=float32)}

In [33]:
nxt

{'diaact': 'request',
 'request_slots': {'release_year': 'UNK'},
 'target': [],
 'probs': [array([0.50925928, 0.49074075, 0.22021661]),
  array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704,
         0.23104693]),
  array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953, 0.22743682]),
  array([0.96883118, 0.01558441, 0.01558441, 0.20577617]),
  array([0.26339287, 0.26339287, 0.20089285, 0.27232143, 0.19133574]),
  array([0.06086956, 0.07391305, 0.07391305, 0.06956521, 0.06086956,
         0.08260869, 0.03478261, 0.04347826, 0.07391305, 0.07826087,
         0.04347826, 0.06956521, 0.03043478, 0.06086956, 0.07826087,
         0.06521739, 0.16967509])],
 'phis': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'posterior': array([0.0036101 , 0.00017191, 0.00017191, 0.00017191, 0.00017191,
        0.0

In [34]:
ua, episode_over, reward = user_sim.next(nxt)

In [35]:
ua

{'diaact': 'inform',
 'turn': 1,
 'inform_slots': {'release_year': '2013'},
 'request_slots': {},
 'prev_diaact': 'request',
 'inform_slots_noisy': {'release_year': '2011'},
 'nl_sentence': 'It is 2011.',
 'episode_over': False,
 'reward': -0.1}

In [36]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  request release_year
Detected 2011  update =  1.0
Agent DB entropy =  4.264997
Agent slot belief entropies - 
actor:0.97 critic_rating:3.00 genre:3.48 mpaa_rating:0.71 director:1.89 release_year:1.72


{'database': <deep_dialog.dialog_system.database.Database at 0x205133656c8>,
 'prevact': 'request@genre',
 'inform_slots': {'actor': array([0.5092593 , 0.49074075], dtype=float32),
  'critic_rating': array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([20.345455 ,  0.3272727,  0.3272727], dtype=float32),
  'director': array([0.26339287, 0.26339287, 0.20089285, 0.27232143], dtype=float32),
  'release_year': array([ 0.06086956,  0.07391305,  0.07391305,  0.06956521,  0.06086956,
          0.08260869,  0.03478261,  0.04347826,  0.07391305,  0.07826087,
          0.04347826, 20.069565  ,  0.03043478,  0.06086956,  0.07826087,
          0.06521739], dtype=

In [37]:
nxt

{'diaact': 'request',
 'request_slots': {'genre': 'UNK'},
 'target': [],
 'probs': [array([0.50925928, 0.49074075, 0.22021661]),
  array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704,
         0.23104693]),
  array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953, 0.22743682]),
  array([0.96883118, 0.01558441, 0.01558441, 0.20577617]),
  array([0.26339287, 0.26339287, 0.20089285, 0.27232143, 0.19133574]),
  array([0.00289855, 0.00351967, 0.00351967, 0.00331263, 0.00289855,
         0.00393375, 0.00165631, 0.00207039, 0.00351967, 0.00372671,
         0.00207039, 0.95569354, 0.00144928, 0.00289855, 0.00372671,
         0.00310559, 0.16967509])],
 'phis': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'posterior': array([1.8884170e-04, 8.9924724e-06, 8.9924724e-06, 8.9924724e-06,
        8.9924724e

In [38]:
ua, episode_over, reward = user_sim.next(nxt)

In [39]:
ua

{'diaact': 'inform',
 'turn': 2,
 'inform_slots': {'genre': None},
 'request_slots': {},
 'prev_diaact': 'inform',
 'inform_slots_noisy': {'genre': None},
 'nl_sentence': 'I dont know',
 'episode_over': False,
 'reward': -0.1}

In [26]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  request genre
Removing slot genre from db!
Agent DB entropy =  4.6841717
Agent slot belief entropies - 
actor:1.00 critic_rating:2.34 genre:0.00 mpaa_rating:0.94 director:1.35 release_year:0.00


{'database': <deep_dialog.dialog_system.database.Database at 0x20513352c08>,
 'prevact': 'request@critic_rating',
 'inform_slots': {'actor': array([0.5092593 , 0.49074075], dtype=float32),
  'critic_rating': array([ 0.10798122,  0.07511737,  0.08450704, 20.16432   ,  0.11267605,
         15.098592  ,  0.08920188,  0.09859155,  0.08450704,  0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([ 0.34545454,  0.3272727 , 20.327272  ], dtype=float32),
  'director': array([15.263392  ,  0.26339287,  0.20089285,  0.27232143], dtype=float32),
  'release_year': array([0.06086956, 0.07391305, 0.07391305, 0.06956521, 0.06086956,
         0.08260869, 0.03478261, 0.04347826, 0.07391305, 0.07826087,
         0.04347826, 0.06956521, 0.03043478, 0.06086956, 0.07826087,
         0.06521739

In [27]:
ua, episode_over, reward = user_sim.next(nxt)

In [28]:
ua

{'diaact': 'inform',
 'turn': 3,
 'inform_slots': {'critic_rating': 'top'},
 'request_slots': {},
 'prev_diaact': 'inform',
 'inform_slots_noisy': {'critic_rating': 'top'},
 'nl_sentence': 'top critic_rating',
 'episode_over': False,
 'reward': -0.1}

In [29]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  request critic_rating
Detected top  update =  1.0
Detected top rated  update =  0.5
Agent DB entropy =  4.578177
Agent slot belief entropies - 
actor:1.00 critic_rating:2.29 genre:0.00 mpaa_rating:0.94 director:1.35 release_year:0.00


{'database': <deep_dialog.dialog_system.database.Database at 0x20513352c08>,
 'prevact': 'request@director',
 'inform_slots': {'actor': array([0.5092593 , 0.49074075], dtype=float32),
  'critic_rating': array([ 0.10798122,  0.07511737,  0.08450704, 50.16432   ,  0.11267605,
         40.09859   ,  0.08920188,  0.09859155,  0.08450704,  0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([ 0.34545454,  0.3272727 , 20.327272  ], dtype=float32),
  'director': array([15.263392  ,  0.26339287,  0.20089285,  0.27232143], dtype=float32),
  'release_year': array([0.06086956, 0.07391305, 0.07391305, 0.06956521, 0.06086956,
         0.08260869, 0.03478261, 0.04347826, 0.07391305, 0.07826087,
         0.04347826, 0.06956521, 0.03043478, 0.06086956, 0.07826087,
         0.06521739], dt

In [33]:
ua, episode_over, reward = user_sim.next(nxt)

In [34]:
ua

{'diaact': 'inform',
 'turn': 4,
 'inform_slots': {'director': 'christopher nolan'},
 'request_slots': {},
 'prev_diaact': 'inform',
 'inform_slots_noisy': {'director': 'christopher nolan'},
 'nl_sentence': 'christopher nolan',
 'episode_over': False,
 'reward': -0.1}

In [35]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  request director
Detected christopher nolan  update =  1.0
Agent DB entropy =  3.8786604
Agent slot belief entropies - 
actor:0.86 critic_rating:0.00 genre:0.00 mpaa_rating:1.06 director:1.72 release_year:2.74


{'database': <deep_dialog.dialog_system.database.Database at 0x1fdc42acc48>,
 'prevact': 'request@mpaa_rating',
 'inform_slots': {'actor': array([15.509259  ,  0.49074075], dtype=float32),
  'critic_rating': array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([0.34545454, 0.3272727 , 0.3272727 ], dtype=float32),
  'director': array([ 0.26339287, 35.263393  ,  0.20089285,  0.27232143], dtype=float32),
  'release_year': array([ 0.06086956,  0.07391305,  0.07391305,  0.06956521,  0.06086956,
          0.08260869,  0.03478261,  0.04347826,  0.07391305,  0.07826087,
          0.04347826,  0.06956521, 20.030436  ,  0.06086956,  0.07826087,
          0.06521

In [36]:
ua, episode_over, reward = user_sim.next(nxt)

In [37]:
ua

{'diaact': 'inform',
 'turn': 5,
 'inform_slots': {'mpaa_rating': None},
 'request_slots': {},
 'prev_diaact': 'inform',
 'inform_slots_noisy': {'mpaa_rating': None},
 'nl_sentence': 'I dont know',
 'episode_over': False,
 'reward': -0.1}

In [40]:
nxt = agent.next(ua, verbose=True)
agent.state

Agent updating state:  request mpaa_rating
Removing slot mpaa_rating from db!
Agent DB entropy =  3.8786607
Agent slot belief entropies - 
actor:0.86 critic_rating:0.00 genre:0.00 mpaa_rating:0.00 director:1.72 release_year:2.74
Agent confident about all slots, inform


{'database': <deep_dialog.dialog_system.database.Database at 0x1fdc42acc48>,
 'prevact': 'inform@inform',
 'inform_slots': {'actor': array([15.509259  ,  0.49074075], dtype=float32),
  'critic_rating': array([0.10798122, 0.07511737, 0.08450704, 0.16431925, 0.11267605,
         0.09859155, 0.08920188, 0.09859155, 0.08450704, 0.08450704],
        dtype=float32),
  'genre': array([0.09345794, 0.08878504, 0.08878504, 0.08411215, 0.07009346,
         0.06542056, 0.03738318, 0.07943925, 0.06074766, 0.07009346,
         0.06542056, 0.08411215, 0.11214953], dtype=float32),
  'mpaa_rating': array([0.34545454, 0.3272727 , 0.3272727 ], dtype=float32),
  'director': array([ 0.26339287, 35.263393  ,  0.20089285,  0.27232143], dtype=float32),
  'release_year': array([ 0.06086956,  0.07391305,  0.07391305,  0.06956521,  0.06086956,
          0.08260869,  0.03478261,  0.04347826,  0.07391305,  0.07826087,
          0.04347826,  0.06956521, 20.030436  ,  0.06086956,  0.07826087,
          0.06521739], 

In [36]:
ua, episode_over, reward = user_sim.next(nxt)

In [37]:
ua

{'diaact': 'inform',
 'turn': 5,
 'inform_slots': {'mpaa_rating': None},
 'request_slots': {},
 'prev_diaact': 'inform',
 'inform_slots_noisy': {'mpaa_rating': None},
 'nl_sentence': 'I dont know',
 'episode_over': False,
 'reward': -0.1}

In [52]:
import numpy as np
import time

N = 1 # количество симуляций


user_sim = RuleSimulator(movie_dict=movie_kb, act_set=act_set, slot_set=slot_set, 
                         start_set=None, max_turn=max_turn, nlg=nlg, err_prob=err_prob, 
                         db=db_full, dk_prob=(1.-dk_prob), sub_prob=sub_prob, 
                         max_first_turn=max_first_turn)

agent = AgentActRule(movie_kb, act_set, slot_set, db_inc,
            upd=params['upd'], tr=params['tr'], ts=params['ts'], 
            frac=params['frac'], max_req=params['max_req'])

dialog_manager = DialogManager(agent, user_sim, db_full, db_inc, movie_kb, verbose=True)

In [53]:
all_rewards = np.zeros((N,))
all_success = np.zeros((N,))
all_turns = np.zeros((N,))
tst = time.time()

for i in range(N):
    current_reward = 0
    current_success = False
    ua = dialog_manager.initialize_episode()
    utt = ua['nl_sentence']
    print('UTT: ', utt)
    t = 0
    while(True):
        t += 1
        episode_over, reward, ua, sa = dialog_manager.next_turn()
        utt = ua['nl_sentence']
        print(utt)
        current_reward += reward
        if episode_over:
            if reward > 0:
                print ("Successful Dialog! Total reward = {}".format(current_reward))
                current_success = True
            else:
                print ("Failed Dialog! Total reward = {}".format(current_reward))
            break
    all_rewards[i] = current_reward
    all_success[i] = 1 if current_success else 0
    all_turns[i] = t

У искомой сущности есть слоты (в неполной БД) ['critic_rating', 'genre', 'director']
Пользователь уже назвал (?): {'genre': 'action', 'director': 'zack snyder'}
User target =  movie:interstellar, actor:tina fey, critic_rating:8%, genre:action, mpaa_rating:r, director:zack snyder, release_year:2001
User information =  critic_rating:8%, genre:action, director:zack snyder 

UTT:  I am looking for a movie with director zack snyder and genre action.
Turn 0 user action: request 	 inform slots: {'genre': 'action', 'director': 'zack snyder'}
Utterance: I am looking for a movie with director zack snyder and genre action. 

query for lookup [None, None, 'action', None, 'zack snyder', None]
Нашло 35 строк
в запросе участвовали не все слоты и нашелся не один ответ
Энтропии:  {'actor': 1.5525278240272846, 'critic_rating': 3.163740516388646, 'mpaa_rating': 1.919728081444846, 'release_year': 3.5672534608576205}
Turn 1 sys action: request, request slots: {'release_year': 'UNK'}

I cannot remember
Turn

In [47]:
ua, episode_over, reward = user_sim.next(nxt)

Просил 275, нашли на позиции 0


In [42]:
dialog_manager = DialogManager(agent, user_sim, db_full, db_inc, movie_kb, verbose=True)

In [44]:
ua = dialog_manager.initialize_episode()
ua

Пользователь знает ['genre', 'mpaa_rating', 'director']
Симулятор знает {'mpaa_rating': 'r', 'director': 'quentin tarantino'}
User target =  movie:hachi: a dog's tale, actor:ryan reynolds, critic_rating:4.5/5, genre:sci-fi, mpaa_rating:r, director:quentin tarantino, release_year:2004
User information =  genre:sci-fi, mpaa_rating:r, director:quentin tarantino 



{'diaact': 'request',
 'turn': 0,
 'inform_slots': {'mpaa_rating': 'r', 'director': 'quentin tarantino'},
 'request_slots': {'movie': 'UNK'},
 'prev_diaact': 'UNK',
 'inform_slots_noisy': {'mpaa_rating': 'r', 'director': 'christopher'},
 'nl_sentence': 'Can you please tell me a movie whose director is christopher and mpaa_rating is r?',
 'episode_over': False,
 'reward': 0}